# Activation Function example: Sigmoid Function

In [ ]:
import numpy as np
import sklearn

In [ ]:
weights = np.array([.8,.1])
inputs = np.array([25,35])

In [ ]:
def summation_function(vector):
  result = vector.dot(weights)
  return result

def sigmoid_activation_function(sum):
  return 1/(1+(np.exp(-sum)))

#sigmoid_activation_function(summation_function(inputs))

sigmoid_activation_function(-25.5)

8.423463754397692e-12

In [ ]:
inputs = np.array([[0,0], [0,1], [1,0], [1,1]])
inputs.shape

outputs = np.array([[0],[1],[1],[0]])
outputs.shape

weights0 = np.array([[-0.424, -0.740, -0.961],
                    [0.358, -0.577, -0.469]]) #weights for x1 and x2, first array is x1

weights1 = np.array([[-0.017],
                    [-0.893],
                    [0.148]]) #weights from hidden layer to output layer

epochs = 100 #since we can't get 100% accuracy for more complex problems

In [ ]:
input_layer = inputs

In [ ]:
sum_synapse0 = np.dot(input_layer, weights0)
print(sum_synapse0) #first row is sum function for 0,0: 2nd row is for 0,1 and so on


[  1.93  -38.695 -40.44 ]


In [ ]:
hidden_layer = sigmoid_activation_function(sum_synapse0)
hidden_layer

array([8.73249420e-01, 1.56666097e-17, 2.73609487e-18])

In [ ]:
#now we repeat for the hidden layer to output layer
sum_synapse1 = np.dot(hidden_layer, weights1)
print(sum_synapse1)

output_layer = sigmoid_activation_function(sum_synapse1)
output_layer

[-0.01484524]


array([0.49628876])

# We also want to keep track of our errors, which calls for a loss-function

error = correct - prediction, but other error calcs are usable

In [ ]:
outputs
output_layer
print(output_layer)

error_layer = outputs - output_layer
print(error_layer)

average_error = np.mean(abs(error_layer))
average_error

[0.49628876]
[[-0.49628876]
 [ 0.50371124]
 [ 0.50371124]
 [-0.49628876]]


0.5

 ## Sigmiod Derivative Example for Gradient Descent

In [ ]:
def sigmoid_derivative(sigmoid):
  return sigmoid * (1 - sigmoid)

s = sigmoid_activation_function(0.5)
print(s)

a = sigmoid_derivative(s)
print(a)



0.6224593312018546
0.2350037122015945


In [ ]:
def delta_calculator(errors, sigmoid_activations):
     return errors * sigmoid_derivative(sigmoid_activations)

delta_outputs = delta_calculator(error_layer, output_layer)
delta_outputs

array([[-0.12406535],
       [ 0.12592087],
       [ 0.12592087],
       [-0.12406535]])

In [ ]:
#need to transpose for matrix manipulation
weights1_transposed = weights1.T
weights1_transposed



delta_mulitiplied_weight = delta_outputs.dot(weights1_transposed)
delta_mulitiplied_weight

delta_hidden = sigmoid_derivative(hidden_layer) * delta_mulitiplied_weight
delta_hidden

array([[ 2.33446680e-04,  1.73570934e-18, -5.02392776e-20],
       [-2.36938103e-04, -1.76166857e-18,  5.09906552e-20],
       [-2.36938103e-04, -1.76166857e-18,  5.09906552e-20],
       [ 2.33446680e-04,  1.73570934e-18, -5.02392776e-20]])

In [ ]:
print(hidden_layer)
hidden_layer_transpose = hidden_layer.T
#first col is activation value (input for backpropogation) for all 4 inputs
#2nd col is activation value (input for backpropogation) for all 4 inputs vice versa
hidden_input_multby_delta = hidden_layer_transpose.dot(delta_outputs)
hidden_input_multby_delta #now these are the new weights from hidden layer to the output layer

[8.73249420e-01 1.56666097e-17 2.73609487e-18]


ValueError: ignored

In [ ]:
learn_rate = 0.3
#update the weights
weights1 = weights1 + (hidden_input_multby_delta * learn_rate)
weights1 #new hidden layer to output weights

NameError: ignored

In [ ]:
#updating the weights from input to hidden layer
inputs
delta_hidden

inputs_transpose = inputs.T

input_mult_delta_hidden = inputs_transpose.dot(delta_hidden)
input_mult_delta_hidden

weights0 = weights0 + (input_mult_delta_hidden * learn_rate)
weights0 #now weights from input to hidden layers
#first col is x1 and x2 to first node
#second col is x1 and x2 to second node etc.

ValueError: ignored

# Network

In [ ]:
from IPython.utils.contexts import NoOpContext
print("inputs are", inputs)
print("results for said inputs are", outputs)
print("Learn rate = ", learn_rate)

def summation_function(vector):
  result = vector.dot(weights)
  return result

def sigmoid_activation_function(sum):
  return 1/(1+(np.exp(-sum)))


def sigmoid_derivative(sigmoid):
  return sigmoid * (1 - sigmoid)

def delta_calculator(errors, sigmoid_activations):
     return errors * sigmoid_derivative(sigmoid_activations)

def calculate_output(instance):
  hidden_layer = sigmoid_activation_function(np.dot(instance, weights0))
  output_layer = sigmoid_activation_function(np.dot(instance, weights1))
  return output_layer

#weight initializer
def weight_initializer():
  weights0 = np.random(random(2,3))
  weights1 = np.random(random(3,1))


#weights
#for 1 hidden layer, with 2 neurons
print(weights0)
print(weights1)

#can either specify your epochs or just run on autopilot for a threshold



inputs are [25 35]
results for said inputs are [[0]
 [1]
 [1]
 [0]]
Learn rate =  0.3
[[-0.424 -0.74  -0.961]
 [ 0.358 -0.577 -0.469]]
[[-0.017]
 [-0.893]
 [ 0.148]]


## Flower Set

In [ ]:
from sklearn import datasets


iris = datasets.load_iris()

In [ ]:
iris.data
#contains x1, x2, x3, x4

iris.feature_names
print(iris.target)

print(iris.target_names)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
['setosa' 'versicolor' 'virginica']


In [ ]:
inputs = iris.data[0:100]
outputs = iris.target[0:100]

outputs = outputs.reshape(-1,1)


In [ ]:

def summation_function(vector):
  result = vector.dot(weights)
  return result

def sigmoid_activation_function(sum):
  return 1/(1+(np.exp(-sum)))


def sigmoid_derivative(sigmoid):
  return sigmoid * (1 - sigmoid)

def delta_calculator(errors, sigmoid_activations):
     return errors * sigmoid_derivative(sigmoid_activations)

weights0 = 2 * np.random.random((4,3)) - 1
weights1 = 2* np.random.random((3,1)) - 1