# Activation Function example: Sigmoid Function

In [1]:
import numpy as np
import sklearn

In [2]:
weights = np.array([.8,.1])
inputs = np.array([25,35])

In [3]:
def summation_function(vector):
  result = vector.dot(weights)
  return result

def sigmoid_activation_function(sum):
  return 1/(1+(np.exp(-sum)))

#sigmoid_activation_function(summation_function(inputs))

sigmoid_activation_function(-25.5)

8.423463754397692e-12

In [4]:
inputs = np.array([[0,0], [0,1], [1,0], [1,1]])
inputs.shape

outputs = np.array([[0],[1],[1],[0]])
outputs.shape

weights0 = np.array([[-0.424, -0.740, -0.961],
                    [0.358, -0.577, -0.469]]) #weights for x1 and x2, first array is x1

weights1 = np.array([[-0.017],
                    [-0.893],
                    [0.148]]) #weights from hidden layer to output layer

epochs = 100 #since we can't get 100% accuracy for more complex problems

In [5]:
input_layer = inputs

In [6]:
sum_synapse0 = np.dot(input_layer, weights0)
print(sum_synapse0) #first row is sum function for 0,0: 2nd row is for 0,1 and so on


[[ 0.     0.     0.   ]
 [ 0.358 -0.577 -0.469]
 [-0.424 -0.74  -0.961]
 [-0.066 -1.317 -1.43 ]]


In [7]:
hidden_layer = sigmoid_activation_function(sum_synapse0)
hidden_layer

array([[0.5       , 0.5       , 0.5       ],
       [0.5885562 , 0.35962319, 0.38485296],
       [0.39555998, 0.32300414, 0.27667802],
       [0.48350599, 0.21131785, 0.19309868]])

In [8]:
#now we repeat for the hidden layer to output layer
sum_synapse1 = np.dot(hidden_layer, weights1)
print(sum_synapse1)

output_layer = sigmoid_activation_function(sum_synapse1)
output_layer

[[-0.381     ]
 [-0.27419072]
 [-0.25421887]
 [-0.16834784]]


array([[0.40588573],
       [0.43187857],
       [0.43678536],
       [0.45801216]])

# We also want to keep track of our errors, which calls for a loss-function

error = correct - prediction, but other error calcs are usable

In [9]:
outputs
output_layer
print(output_layer)

error_layer = outputs - output_layer
print(error_layer)

average_error = np.mean(abs(error_layer))
average_error

[[0.40588573]
 [0.43187857]
 [0.43678536]
 [0.45801216]]
[[-0.40588573]
 [ 0.56812143]
 [ 0.56321464]
 [-0.45801216]]


0.49880848923713045

 ## Sigmiod Derivative Example for Gradient Descent

In [10]:
def sigmoid_derivative(sigmoid):
  return sigmoid * (1 - sigmoid)

s = sigmoid_activation_function(0.5)
print(s)

a = sigmoid_derivative(s)
print(a)



0.6224593312018546
0.2350037122015945


In [11]:
def delta_calculator(errors, sigmoid_activations):
     return errors * sigmoid_derivative(sigmoid_activations)

delta_outputs = delta_calculator(error_layer, output_layer)
delta_outputs

array([[-0.0978763 ],
       [ 0.13939397],
       [ 0.138553  ],
       [-0.11369557]])

In [12]:
#need to transpose for matrix manipulation
weights1_transposed = weights1.T
weights1_transposed



delta_mulitiplied_weight = delta_outputs.dot(weights1_transposed)
delta_mulitiplied_weight

delta_hidden = sigmoid_derivative(hidden_layer) * delta_mulitiplied_weight
delta_hidden

array([[ 0.00041597,  0.02185088, -0.00362142],
       [-0.00057384, -0.02866677,  0.00488404],
       [-0.00056316, -0.02705587,  0.00410378],
       [ 0.00048268,  0.01692128, -0.00262183]])

In [13]:
print(hidden_layer)
hidden_layer_transpose = hidden_layer.T
#first col is activation value (input for backpropogation) for all 4 inputs
#2nd col is activation value (input for backpropogation) for all 4 inputs vice versa
hidden_input_multby_delta = hidden_layer_transpose.dot(delta_outputs)
hidden_input_multby_delta #now these are the new weights from hidden layer to the output layer

[[0.5        0.5        0.5       ]
 [0.5885562  0.35962319 0.38485296]
 [0.39555998 0.32300414 0.27667802]
 [0.48350599 0.21131785 0.19309868]]


array([[0.03293657],
       [0.02191844],
       [0.02108814]])

In [14]:
learn_rate = 0.3
#update the weights
weights1 = weights1 + (hidden_input_multby_delta * learn_rate)
weights1 #new hidden layer to output weights

array([[-0.00711903],
       [-0.88642447],
       [ 0.15432644]])

In [15]:
#updating the weights from input to hidden layer
inputs
delta_hidden

inputs_transpose = inputs.T

input_mult_delta_hidden = inputs_transpose.dot(delta_hidden)
input_mult_delta_hidden

weights0 = weights0 + (input_mult_delta_hidden * learn_rate)
weights0 #now weights from input to hidden layers
#first col is x1 and x2 to first node
#second col is x1 and x2 to second node etc.

array([[-0.42402414, -0.74304038, -0.96055542],
       [ 0.35797265, -0.58052365, -0.46832134]])

# Network

In [16]:
from IPython.utils.contexts import NoOpContext
print("inputs are", inputs)
print("results for said inputs are", outputs)
print("Learn rate = ", learn_rate)

def summation_function(vector):
  result = vector.dot(weights)
  return result

def sigmoid_activation_function(sum):
  return 1/(1+(np.exp(-sum)))


def sigmoid_derivative(sigmoid):
  return sigmoid * (1 - sigmoid)

def delta_calculator(errors, sigmoid_activations):
     return errors * sigmoid_derivative(sigmoid_activations)

def calculate_output(instance):
  hidden_layer = sigmoid_activation_function(np.dot(instance, weights0))
  output_layer = sigmoid_activation_function(np.dot(instance, weights1))
  return output_layer

#weight initializer
def weight_initializer():
  weights0 = np.random(random(2,3))
  weights1 = np.random(random(3,1))


#weights
#for 1 hidden layer, with 2 neurons
print(weights0)
print(weights1)

#can either specify your epochs or just run on autopilot for a threshold



inputs are [[0 0]
 [0 1]
 [1 0]
 [1 1]]
results for said inputs are [[0]
 [1]
 [1]
 [0]]
Learn rate =  0.3
[[-0.42402414 -0.74304038 -0.96055542]
 [ 0.35797265 -0.58052365 -0.46832134]]
[[-0.00711903]
 [-0.88642447]
 [ 0.15432644]]


## Flower Set

In [17]:
from sklearn import datasets


iris = datasets.load_iris()

In [18]:
iris.data
#contains x1, x2, x3, x4

iris.feature_names
print(iris.target)

print(iris.target_names)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
['setosa' 'versicolor' 'virginica']


In [19]:
inputs = iris.data[0:100]
outputs = iris.target[0:100]

outputs = outputs.reshape(-1,1)


In [20]:

def summation_function(vector):
  result = vector.dot(weights)
  return result

def sigmoid_activation_function(sum):
  return 1/(1+(np.exp(-sum)))


def sigmoid_derivative(sigmoid):
  return sigmoid * (1 - sigmoid)

def delta_calculator(errors, sigmoid_activations):
     return errors * sigmoid_derivative(sigmoid_activations)

weights0 = 2 * np.random.random((4,3)) - 1
weights1 = 2* np.random.random((3,1)) - 1